### ISSUE TITLE
Need to support easy import/export from SolarSoft IDL FITS files containing visibilities

### ISSUE THREAD

**Issue by pgabor** [sunpy/xrayvision#2]
Need to support easy import/export from SolarSoft IDL FITS files containing visibilities  <-> our python class and then from our class back SolarSoft compatible FITS files

**Comment by samaloney** [comment]
Once the repo is operational I'll upload some sample fits files of increasing complexity, single time and energy range, multiple time or energy ranges and finally multiple time and energy ranges. The reading and writing of the files should be trivial but the computation of some of the parameters might no be so simple.

**Comment by dpshelio** [comment]
I wouldn't put the files in the repo unless they are very small, and needed for testing - we should use a different place to put data (it could be a different repo if needed... but I would start putting them somewhere that's not a repo, e.g. dropbox or some other website).

**Comment by samaloney** [comment]
Yea that was my plan they would be basis for tests or demos so need to be in the repo somewhere.

**Comment by dpshelio** [comment]
For demos in sunpy we have a separate repository, and @ehsteve has recently created a way to allow other packages to use the same tool (sunpy/sunpy#2116). So we should do the same as they are doing for IRIS.
For testing, yes, they should be part of this repository... but very small :)
