### ISSUE TITLE
Create a class to represent visibilities / visibility data

### ISSUE THREAD

**Issue by samaloney** [sunpy/xrayvision#4]
The current SolarSoft/IDL structure is shown below, it will probably be necessary to keep the same fields but each visibility reproduces the entire structure. Certain elements will be the same for a group or set of visibilities such as erange, trange, xyoffset while other elements vary so could be encoded as numpy arrays (u, v, obsvis, ...). 

Also some elements are specific to certain instruments (RHESSI) and may not be meaningful/usefull in general.

```
;  ;    IDL> help, va,/st
;  ;    ** Structure HSI_VIS, 15 tags, length=112, data length=102:
;  ;    ISC             INT              0								<- related to the grid/detector
;  ;    HARM            INT              1								<- harmonic used
;  ;    ERANGE          FLOAT     Array[2]							<- energy range
;  ;    TRANGE          DOUBLE    Array[2]						<- time range
;  ;    U               FLOAT          0.220757							<- u coordinate in Fourier space
;  ;    V               FLOAT         0.0105845						<- v coordinate in Fourier space
;  ;    OBSVIS          COMPLEX   (      7.28559,      11.1368)			<- complex Fourier component
;  ;    TOTFLUX         FLOAT          0.000000						<- total flux
;  ;    SIGAMP          FLOAT           245.240						<- simga or error on visibility
;  ;    CHI2            FLOAT           1.00000						<- chi squared from fit
;  ;    XYOFFSET        FLOAT     Array[2]						<- off set from Sun centre
;  ;    TYPE            STRING    'photon'							<- count, photon, electron
;  ;    UNITS           STRING    'Photons cm!u-2!n s!u-1!n'			<- units
;  ;    ATTEN_STATE     INT              1							<- state of the attenuator
;  ;    COUNT           FLOAT           10764.4						<- detector counts
```

**Comment by samaloney** [comment]
So we have a basic class now need to sub class to support extra info

**Comment by pgabor** [comment]
Should we stay with the idl provided names or improvise based on the documentation?

**Comment by samaloney** [comment]
We need to carry the same information as in the IDL code so I think keep the names or similar names. They don't need to be arrays they should be the same for a set of visibility the only arrays should the ones we already have so use that as a base class.

**Comment by pgabor** [comment]
Fair enough :)
