### ISSUE TITLE
Create visibilities from a SunPy map

### ISSUE THREAD

**Issue by samaloney** [sunpy/xrayvision#5]
Create an arbitrary SunPy map (e.g. disk centre, 65x65 wth 1 arcsec pixels)
- with a singe pixel of 1 at the centre
- with a gaussian source or distribution at the centre
take an arbitrary sampling of the u, v plane and compute the corresponding visibilities.

- [] Depends on #4

**Comment by pgabor** [comment]
So you mean to provide an ability to interpret sunpy maps as "image" inputs? And what about visibilities? Another Sunpy map with a dirty beam?

**Comment by samaloney** [comment]
Yea I mean a map is really just and image with coordinate axes rather then pixel. So take a map extract the image and coordinate and feed into the code we have map code we have.
